### ISSUE TITLE
Add AWS Secrets Manager

### ISSUE THREAD

**Issue by nagiyu** [nagiyu/open-hands-demo#25]
GitHub Actions のシークレット取得に AWS の SecretsManager を採用する。

### 対応
- PAT_TOKEN: シークレット名: GitHub, キー名: PERSONAL_ACCESS_TOKEN
- PAT_USERNAME: シークレット名: GitHub, キー名: USERNAME
- LLM_API_KEY: シークレット名: OpenAI, キー名: OPEN_HANDS_API_KEY

### サンプル
```
    - name: AWS CLI install
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version

    - name: AWS set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get Google secrets from AWS SecretsManager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          GOOGLE_OAUTH_SECRETS, NiconicoMylistAssistant/Manager/Google
        parse-json-secrets: true
```
この場合、`GOOGLE_CLIENT_ID` は `${{ env.GOOGLE_OAUTH_SECRETS_GOOGLE_CLIENT_ID }}` と取得できる。
